package de.objectcode.soatools.test.webservicein.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.1-07/21/2008 10:18
 * AM(brewbuilder)- Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WebserviceInWSService", targetNamespace = "http://objectcode.de/test/webservicein", wsdlLocation = "file:/Users/junglas/workspaces/w7/soatools/test/director/integration/src/it/resources/webservice-in.wsdl")
public class WebserviceInWSService extends Service {

	private final static URL WEBSERVICEINWSSERVICE_WSDL_LOCATION;

	static {
		WEBSERVICEINWSSERVICE_WSDL_LOCATION = WebserviceInWSService.class
				.getClassLoader().getResource("webservice-in.wsdl");
	}

	public WebserviceInWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WebserviceInWSService() {
		super(WEBSERVICEINWSSERVICE_WSDL_LOCATION, new QName(
				"http://objectcode.de/test/webservicein",
				"WebserviceInWSService"));
	}

	/**
	 * 
	 * @return returns WebserviceIn
	 */
	@WebEndpoint(name = "WebserviceInPort")
	public WebserviceIn getWebserviceInPort() {
		return (WebserviceIn) super.getPort(new QName(
				"http://objectcode.de/test/webservicein", "WebserviceInPort"),
				WebserviceIn.class);
	}

}
