
package de.objectcode.soatools.test.webservicein.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-07/21/2008 10:18 AM(brewbuilder)-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebserviceIn", targetNamespace = "http://objectcode.de/test/webservicein")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebserviceIn {


    /**
     * 
     * @param message
     * @param serviceCategory
     * @param serviceName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "success", partName = "success")
    public boolean routeMessage(
        @WebParam(name = "serviceCategory", partName = "serviceCategory")
        String serviceCategory,
        @WebParam(name = "serviceName", partName = "serviceName")
        String serviceName,
        @WebParam(name = "message", partName = "message")
        EsbMessage message);

}
