
package de.objectcode.soatools.msmq.outgoing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MsmqOutGatewayPortType", targetNamespace = "http://liwest.at/msmq/outgoing")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MsmqOutGatewayPortType {


    /**
     * 
     * @param destination
     * @param message
     * @return
     *     returns boolean
     */
    @WebMethod(action = "routeMessage")
    @WebResult(partName = "return")
    public boolean routeMessage(
        @WebParam(name = "destination", partName = "destination")
        String destination,
        @WebParam(name = "message", partName = "message")
        MsmqOutMessage message);

}
