package de.objectcode.soatools.msmq.outgoing;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.1-b03- Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "MsmqOutGatewayService", targetNamespace = "http://liwest.at/msmq/outgoing")
public class MsmqOutGatewayService extends Service
{

  private final static URL MSMQOUTGATEWAYSERVICE_WSDL_LOCATION;

  static {
    MSMQOUTGATEWAYSERVICE_WSDL_LOCATION = MsmqOutGatewayService.class.getClassLoader().getResource("MsmqGateway.wsdl");
  }

  public MsmqOutGatewayService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  public MsmqOutGatewayService()
  {
    super(MSMQOUTGATEWAYSERVICE_WSDL_LOCATION, new QName("http://liwest.at/msmq/outgoing", "MsmqOutGatewayService"));
  }

  /**
   * 
   * @return returns MsmqOutGatewayPortType
   */
  @WebEndpoint(name = "MsmqOutGatewayPort")
  public MsmqOutGatewayPortType getMsmqOutGatewayPort()
  {
    return super.getPort(new QName("http://liwest.at/msmq/outgoing", "MsmqOutGatewayPort"),
        MsmqOutGatewayPortType.class);
  }

}
