
package de.objectcode.soatools.test.mock.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MockWebServiceControlWS", targetNamespace = "http://objectcode.de/test/mock/webservice")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MockWebServiceControlWS {


    /**
     * 
     */
    @WebMethod
    public void clearCalls();

    /**
     * 
     * @return
     *     returns de.objectcode.soatools.test.mock.webservice.client.CallList
     */
    @WebMethod
    @WebResult(name = "calls", partName = "calls")
    public CallList getCalls();

}
